spring:
  server:
    port: 8080
  web:
    resources:
      add-mappings: false   # 关闭静态资源映射，适用于前后端分离
  mvc:
    path match:
      matching-strategy: ant_path_matcher  #
#    web:
#      resources:
#        static-locations: classpath:/static/
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 5000
      lettuce:
        pool:
          max-active: 10
          max-idle: 8
          min-idle: 0
          max-wait: 1000ms

  datasource:
    url: jdbc:mysql://localhost:3306/swith_chat?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: a132b465
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 200MB  # 设置上传单个文件的最大大小
      max-request-size: 200MB  # 设置整个请求的最大大小

  rabbitmq:
    host: localhost  # RabbitMQ 服务器地址
    port: 5672       # 默认端口
    username: guest  # 默认用户名
    password: guest  # 默认密码
    virtual-host: /


minio:
  endpoint: http://localhost:9000  # MinIO 服务器地址
  access-key: minioadmin          # 访问密钥（默认）
  secret-key: minioadmin          # 密钥（默认）
  bucket-name: first-chat        # 默认存储桶



mybatis:
#  mapper-locations: classpath:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

captcha:
  enable-captcha: false   #这个是测试环境关闭验证码
